### ISSUE TITLE
phase1.azure.use_ephemeral_drive not found

### ISSUE THREAD

**Issue by francesconero** [colemickens/azure-kubernetes-demo#3]
I'm sorry if this repo shouldn't be used, but I had no luck using other methods for deploying k8s on Azure.

Following instructions as is, fails to deploy the master node because it seems to be missing the value `phase1.azure.use_ephemeral_drive`.

Adding it to the phase1/azure/Kconfig file (in the dev container) seems to fix the problem, and I was able to deploy a cluster.

Also you have to choose the cluster name to be globally unique, since it gets used to name a storage account.

**Comment by colemickens** [comment]
> I'm sorry if this repo shouldn't be used, but I had no luck using other methods for deploying k8s on Azure.

This is a fine place to put feedback for the Kubernetes-Anywhere bringup. Thanks for taking time to report it.

> Following instructions as is, fails to deploy the master node because it seems to be missing the value phase1.azure.use_ephemeral_drive.
> 
> Adding it to the phase1/azure/Kconfig file (in the dev container) seems to fix the problem, and I was able to deploy a cluster.

I actually received this feedback yesterday as well. The `phase1.azure.use_ephemeral_drive` problem is because the installation container was published from a WIP PR branch. I'll either get the PR pushed in or rollback the install container to fix this. I'm hoping to do that over the weekend.

> Also you have to choose the cluster name to be globally unique, since it gets used to name a storage account.

I plan to add something to help with this as well. Either a check ahead of time, a unique hash suffix  or both.

**Comment by francesconero** [comment]
> I'll either get the PR pushed in or rollback the install container to fix this. I'm hoping to do that over the weekend.

Awesome, thanks!
Is it ok if in the meanwhile I use the workaround I mentioned?

**Comment by colemickens** [comment]
Yes, it would be okay.

However, things have just changed again and the docs are out of date again. I'm going to get them patched up in the next day or two and moved into the kubernetes-anywhere repo properly where they will be updated to stay accurate with the actual state of kubernetes-anywhere.

**Comment by colemickens** [comment]
This is resolved now, as those features have been abandoned. They'll be re-added at some point in the future.
